// Comprehensive exercise library with taxonomy and sub-region mappings
import { Exercise } from '../types/workout';

export const EXERCISE_LIBRARY: Exercise[] = [
  // ============= CHEST EXERCISES =============
  {
    id: 'bench-press',
    name: 'Bench Press',
    movementCategory: 'horizontal-push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'chest-mid', weight: 0.7 },
      { region: 'chest-upper', weight: 0.2 },
      { region: 'chest-lower', weight: 0.1 },
    ],
    substitutions: ['dumbbell-press', 'incline-bench-press'],
    formNotes: 'Retract scapula, feet flat, slight arch. Lower to chest with control.',
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    movementCategory: 'horizontal-push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'chest-upper', weight: 0.8 },
      { region: 'chest-mid', weight: 0.2 },
    ],
    substitutions: ['incline-dumbbell-press'],
    formNotes: '30-45 degree angle. Focus on upper chest.',
    limitations: ['shoulder-friendly'],
  },
  {
    id: 'decline-bench-press',
    name: 'Decline Bench Press',
    movementCategory: 'horizontal-push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'chest-lower', weight: 0.8 },
      { region: 'chest-mid', weight: 0.2 },
    ],
    substitutions: ['dips'],
  },
  {
    id: 'dumbbell-press',
    name: 'Dumbbell Press',
    movementCategory: 'horizontal-push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['dumbbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'chest-mid', weight: 0.7 },
      { region: 'chest-upper', weight: 0.2 },
      { region: 'chest-lower', weight: 0.1 },
    ],
    substitutions: ['bench-press'],
    formNotes: 'Greater ROM than barbell. Can rotate wrists.',
    limitations: ['shoulder-friendly'],
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    movementCategory: 'horizontal-push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'chest-upper', weight: 0.8 },
      { region: 'chest-mid', weight: 0.2 },
    ],
    substitutions: ['incline-bench-press'],
  },
  {
    id: 'dips',
    name: 'Dips',
    movementCategory: 'vertical-push',
    primaryMuscles: ['chest', 'triceps'],
    secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'chest-lower', weight: 0.6 },
      { region: 'triceps', weight: 0.4 },
    ],
    substitutions: ['decline-bench-press'],
    formNotes: 'Lean forward for chest. Keep elbows out.',
  },
  {
    id: 'push-ups',
    name: 'Push-ups',
    movementCategory: 'horizontal-push',
    primaryMuscles: ['chest'],
    secondaryMuscles: ['triceps', 'shoulders', 'core'],
    equipment: ['bodyweight'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'chest-mid', weight: 0.6 },
      { region: 'chest-lower', weight: 0.2 },
      { region: 'triceps', weight: 0.2 },
    ],
    substitutions: ['bench-press'],
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    movementCategory: 'isolation',
    primaryMuscles: ['chest'],
    secondaryMuscles: [],
    equipment: ['cable'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'chest-mid', weight: 1.0 },
    ],
    substitutions: ['dumbbell-fly'],
  },

  // ============= BACK EXERCISES =============
  {
    id: 'deadlift',
    name: 'Deadlift',
    movementCategory: 'hinge',
    primaryMuscles: ['back', 'glutes', 'hamstrings'],
    secondaryMuscles: ['quads', 'forearms'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'back-erectors', weight: 0.5 },
      { region: 'glutes', weight: 0.3 },
      { region: 'hamstrings', weight: 0.2 },
    ],
    substitutions: ['romanian-deadlift'],
    formNotes: 'Hinge at hips, neutral spine. Drive through heels.',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    movementCategory: 'horizontal-pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps', 'forearms'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'back-lats', weight: 0.5 },
      { region: 'back-upper', weight: 0.5 },
    ],
    substitutions: ['dumbbell-row'],
    formNotes: 'Pull to lower chest. 45 degree torso.',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    movementCategory: 'horizontal-pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    isUnilateral: true,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'back-lats', weight: 0.6 },
      { region: 'back-upper', weight: 0.4 },
    ],
    substitutions: ['barbell-row'],
  },
  {
    id: 'pull-ups',
    name: 'Pull-ups',
    movementCategory: 'vertical-pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['bodyweight'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'back-lats', weight: 0.8 },
      { region: 'back-upper', weight: 0.2 },
    ],
    substitutions: ['lat-pulldown'],
    formNotes: 'Full ROM. Pull chest to bar.',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    movementCategory: 'vertical-pull',
    primaryMuscles: ['back'],
    secondaryMuscles: ['biceps'],
    equipment: ['cable', 'machine'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'back-lats', weight: 0.8 },
      { region: 'back-upper', weight: 0.2 },
    ],
    substitutions: ['pull-ups'],
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    movementCategory: 'horizontal-pull',
    primaryMuscles: ['shoulders', 'back'],
    secondaryMuscles: [],
    equipment: ['cable'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'shoulders-posterior', weight: 0.6 },
      { region: 'back-upper', weight: 0.4 },
    ],
    substitutions: ['rear-delt-fly'],
    limitations: ['shoulder-friendly'],
  },

  // ============= SHOULDER EXERCISES =============
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    movementCategory: 'vertical-push',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'shoulders-anterior', weight: 0.6 },
      { region: 'shoulders-lateral', weight: 0.3 },
      { region: 'back-upper', weight: 0.1 },
    ],
    substitutions: ['dumbbell-shoulder-press'],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    movementCategory: 'vertical-push',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'shoulders-anterior', weight: 0.6 },
      { region: 'shoulders-lateral', weight: 0.4 },
    ],
    substitutions: ['overhead-press'],
    limitations: ['shoulder-friendly'],
  },
  {
    id: 'lateral-raises',
    name: 'Lateral Raises',
    movementCategory: 'isolation',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'shoulders-lateral', weight: 1.0 },
    ],
    substitutions: [],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    movementCategory: 'isolation',
    primaryMuscles: ['shoulders'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'cable'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'shoulders-posterior', weight: 0.8 },
      { region: 'back-upper', weight: 0.2 },
    ],
    substitutions: ['face-pulls'],
  },

  // ============= ARM EXERCISES =============
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    movementCategory: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: ['forearms'],
    equipment: ['barbell', 'ez-bar'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'biceps', weight: 1.0 },
    ],
    substitutions: ['dumbbell-curl'],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    movementCategory: 'isolation',
    primaryMuscles: ['biceps'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'biceps', weight: 1.0 },
    ],
    substitutions: ['barbell-curl'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    movementCategory: 'isolation',
    primaryMuscles: ['biceps', 'forearms'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'biceps', weight: 0.7 },
      { region: 'forearms', weight: 0.3 },
    ],
    substitutions: ['dumbbell-curl'],
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    movementCategory: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['cable'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'triceps', weight: 1.0 },
    ],
    substitutions: ['skull-crushers'],
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    movementCategory: 'isolation',
    primaryMuscles: ['triceps'],
    secondaryMuscles: [],
    equipment: ['barbell', 'ez-bar'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'triceps', weight: 1.0 },
    ],
    substitutions: ['overhead-tricep-extension'],
  },
  {
    id: 'close-grip-bench',
    name: 'Close Grip Bench Press',
    movementCategory: 'horizontal-push',
    primaryMuscles: ['triceps', 'chest'],
    secondaryMuscles: [],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'triceps', weight: 0.6 },
      { region: 'chest-mid', weight: 0.4 },
    ],
    substitutions: ['dips'],
  },

  // ============= LEG EXERCISES =============
  {
    id: 'squat',
    name: 'Squat',
    movementCategory: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: ['hamstrings', 'core'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'quads', weight: 0.5 },
      { region: 'glutes', weight: 0.4 },
      { region: 'back-erectors', weight: 0.1 },
    ],
    substitutions: ['front-squat', 'leg-press'],
    formNotes: 'Break at hips and knees. Chest up. Drive through heels.',
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    movementCategory: 'squat',
    primaryMuscles: ['quads'],
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'quads', weight: 0.7 },
      { region: 'glutes', weight: 0.2 },
      { region: 'core-upper', weight: 0.1 },
    ],
    substitutions: ['squat'],
    limitations: ['knee-friendly'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    movementCategory: 'hinge',
    primaryMuscles: ['hamstrings', 'glutes'],
    secondaryMuscles: ['back'],
    equipment: ['barbell', 'dumbbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'hamstrings', weight: 0.6 },
      { region: 'glutes', weight: 0.4 },
    ],
    substitutions: ['deadlift'],
    formNotes: 'Hinge at hips. Feel stretch in hamstrings.',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    movementCategory: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: [],
    equipment: ['machine'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'quads', weight: 0.6 },
      { region: 'glutes', weight: 0.4 },
    ],
    substitutions: ['squat'],
    limitations: ['knee-friendly'],
  },
  {
    id: 'lunges',
    name: 'Lunges',
    movementCategory: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: [],
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    isUnilateral: true,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'quads', weight: 0.5 },
      { region: 'glutes', weight: 0.5 },
    ],
    substitutions: ['bulgarian-split-squat'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    movementCategory: 'squat',
    primaryMuscles: ['quads', 'glutes'],
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    isUnilateral: true,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'quads', weight: 0.6 },
      { region: 'glutes', weight: 0.4 },
    ],
    substitutions: ['lunges'],
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    movementCategory: 'isolation',
    primaryMuscles: ['hamstrings'],
    secondaryMuscles: [],
    equipment: ['machine'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'hamstrings', weight: 1.0 },
    ],
    substitutions: ['romanian-deadlift'],
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    movementCategory: 'isolation',
    primaryMuscles: ['quads'],
    secondaryMuscles: [],
    equipment: ['machine'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'quads', weight: 1.0 },
    ],
    substitutions: [],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    movementCategory: 'hinge',
    primaryMuscles: ['glutes'],
    secondaryMuscles: ['hamstrings'],
    equipment: ['barbell'],
    isUnilateral: false,
    trackE1RM: true,
    subRegionWeights: [
      { region: 'glutes', weight: 1.0 },
    ],
    substitutions: [],
    formNotes: 'Upper back on bench. Drive through heels.',
  },
  {
    id: 'calf-raises',
    name: 'Calf Raises',
    movementCategory: 'isolation',
    primaryMuscles: ['calves'],
    secondaryMuscles: [],
    equipment: ['machine', 'dumbbell'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'calves', weight: 1.0 },
    ],
    substitutions: [],
  },

  // ============= CORE EXERCISES =============
  {
    id: 'plank',
    name: 'Plank',
    movementCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'core-upper', weight: 0.6 },
      { region: 'core-lower', weight: 0.4 },
    ],
    substitutions: [],
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    movementCategory: 'core',
    primaryMuscles: ['obliques'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    isUnilateral: true,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'obliques', weight: 1.0 },
    ],
    substitutions: [],
  },
  {
    id: 'cable-crunches',
    name: 'Cable Crunches',
    movementCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['cable'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'core-upper', weight: 0.8 },
      { region: 'core-lower', weight: 0.2 },
    ],
    substitutions: [],
  },
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    movementCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'core-lower', weight: 0.8 },
      { region: 'core-upper', weight: 0.2 },
    ],
    substitutions: [],
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists',
    movementCategory: 'core',
    primaryMuscles: ['obliques'],
    secondaryMuscles: [],
    equipment: ['bodyweight', 'dumbbell'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'obliques', weight: 1.0 },
    ],
    substitutions: [],
  },
  {
    id: 'ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    movementCategory: 'core',
    primaryMuscles: ['core'],
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    isUnilateral: false,
    trackE1RM: false,
    subRegionWeights: [
      { region: 'core-upper', weight: 0.7 },
      { region: 'core-lower', weight: 0.3 },
    ],
    substitutions: ['plank'],
  },
];

// Helper functions
export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find(ex => ex.id === id);
}

export function getExerciseByName(name: string): Exercise | undefined {
  return EXERCISE_LIBRARY.find(
    ex => ex.name.toLowerCase() === name.toLowerCase()
  );
}

export function searchExercises(query: string): Exercise[] {
  const lowerQuery = query.toLowerCase();
  return EXERCISE_LIBRARY.filter(ex =>
    ex.name.toLowerCase().includes(lowerQuery) ||
    ex.primaryMuscles.some(m => m.toLowerCase().includes(lowerQuery)) ||
    ex.movementCategory.toLowerCase().includes(lowerQuery)
  );
}

export function getExercisesByMuscle(muscle: string): Exercise[] {
  return EXERCISE_LIBRARY.filter(ex => 
    ex.primaryMuscles.includes(muscle as any)
  );
}

export function getExercisesByEquipment(equipment: string): Exercise[] {
  return EXERCISE_LIBRARY.filter(ex => 
    ex.equipment.includes(equipment as any)
  );
}

